version: '3.8'

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:13-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_test
  web:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - db_test
volumes:
  postgres_data: